### PR TITLE
Fix callback attributes in MOI.ListOfModelAttributesSet

### LINKED ISSUE #579: ListOfModelAttributesSet does not include callbacks
Hey! 

As the title says, we get an error when printing in `LP` format with Gurobi:
```
ERROR: MathOptInterface.UnsupportedAttribute{Gurobi.CallbackFunction}: Attribute Gurobi.CallbackFunction() is not supported by the model.
Stacktrace:
```
Here is a MRE on the latest version `1.3.1` of Gurobi.jl.

```
import Gurobi
import MathOptInterface as MOI

model = MOI.instantiate(() -> Gurobi.Optimizer(); with_cache_type = Float64, with_bridge_type = Float64)
MOI.set(model, Gurobi.CallbackFunction(), () -> nothing)
MOI.Utilities.loadfromstring!(
           model,
           """
       variables: x, y, z
       minobjective: 1.0 * x + 1.0 * y + 1.0 * z
       c1: x + y == 2.0
       c2: x + y + z >= 0.0
       c3: 1.0 * x * x + -1.0 * y * y + -1.0 * z * z >= 0.0
       x >= 0.0
       y >= 0.0
       z >= 0.0
       """)
print_options = (; format = MOI.FileFormats.FORMAT_LP)
dest = MOI.FileFormats.Model(; print_options...)
MOI.copy_to(dest, model)
```

If I omit the line that sets the `Gurobi.CallbackFunction`, printing works. Also using the `Gurobi.Optimizer()` directly instead of a cached optimizer works.

Edit: I thought we could set `CallbackFunction` to `nothing` before printing but that unfortunately resets the optimizer state. Printing works correctly in that case.

Thank you!

### PR DESCRIPTION
**Pull request by odow**
Closes #579

### CODE REVIEW

File: test/MOI/MOI_callbacks.jl [hunk 1]
```diff
@@ -443,6 +470,12 @@ function test_CallbackFunction_callback_LazyConstraint()
     @test Gurobi.GRB_CB_MESSAGE in cb_calls
     @test Gurobi.GRB_CB_PRESOLVE in cb_calls
     @test Gurobi.GRB_CB_MIPSOL in cb_calls
+    attrs = MOI.get(model, MOI.ListOfModelAttributesSet())
+    @test Gurobi.CallbackFunction() in attrs
+    MOI.set(model, MOI.CallbackFunction(), nothing)
```
Comment (odow) [inline test/MOI/MOI_callbacks.jl:475]:
```suggestion
    MOI.set(model, Gurobi.CallbackFunction(), nothing)
```

File: test/MOI/MOI_callbacks.jl [hunk 2]
```diff
@@ -443,6 +470,12 @@ function test_CallbackFunction_callback_LazyConstraint()
...
+    attrs = MOI.get(model, MOI.ListOfModelAttributesSet())
+    @test !(MOI.CallbackFunction() in attrs)
```
Comment (odow) [inline test/MOI/MOI_callbacks.jl:477]:
```suggestion
    @test !(Gurobi.CallbackFunction() in attrs)
```
